id: org.ksmster.git-sidecar
version: 0.0.1
type: Che Plugin
name: git-sidecar
title: Git sidecar
description: Git sidecar
url: https://github.com/skabashnyuk/che-plugin-git/raw/git/org.ksmster.git-sidecar/0.0.1/che-plugin-git.tar.gz
